version: '3.10'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  php-mongodb-api-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-mongodb-api-web
    networks:
      - mynetwork
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    depends_on:
      - php-mongodb-api-web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - mynetwork

  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
